### ISSUE TITLE
Seeing the wits posted by a user on their profile

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#102]
The user should be able to see people's wits when accessing their profile. Also, the user can react to this wits even if he didn't follow the person #83

**Comment by RobertBeaudenon** [comment]
To populate the wits on the profile :
1- I created the' services ' Folder in profile with the required files.
2-The Array of object 'userWits' can be directly used in the Html body to retrieve the wits.
3- I am also getting the Number of Likes for each userWit accessible with 'likesListProfile'
