### ISSUE TITLE
Token Intercepter 

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#105]
We need token Intercepter

**Comment by AlainJobs** [comment]
Issue resolved. --.> What's been done upon closing this issue: 

After some time of checking all possibilities for handling token and HTTP responses/requests, I found a straightforward way. I added a small file called token-interceptor.service.ts and added some tweaks in the auth.service.ts as well as the app.module.ts. I tested it also upon login and I'm able to retrieve the token from one of the multiple events. I will still have to understand a bit further everything related to http/token responses/requests but I know that we could do very powerful things. i.e for login/logout authentification for instance. I attached a pic to show you exactly how I tested it. 
We should meet before talking about how we could implement it in our project. 

Fixes #105 
![httptoken](https://user-images.githubusercontent.com/33582344/52918415-b8fbcf80-32c4-11e9-8556-e5320f0b8216.PNG)
