### ISSUE TITLE
User can see the followers of their followers 

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#109]
The user can see the list of people their followers are following. #107

**Comment by bernzclav** [comment]
Implementation done.

**Comment by csbduzi** [comment]
Acceptance TEST PASS: 

![screen shot 2019-03-06 at 6 34 24 pm](https://user-images.githubusercontent.com/46238950/53921507-a7455680-403e-11e9-9575-4cbcc5b38ddf.png)
