### ISSUE TITLE
User can like comments

### ISSUE THREAD

**Issue by AlainJobs** [mohanadarafe/s341-witwit#110]
user can like any comment they want. regardless if they know the person or no. Refer to feature #37

**Comment by Hambrsoom** [comment]
Just like for wits, user can't like their own replies.

**Comment by Hambrsoom** [comment]
![image](https://user-images.githubusercontent.com/32947679/53684843-a29c3d80-3ce0-11e9-8a4c-7c30bdc2cb0f.png)

**Comment by Hambrsoom** [comment]
After liking a reply: A user can unlike a reply. 

![image](https://user-images.githubusercontent.com/32947679/53689566-05b0c300-3d27-11e9-80c4-515d91eea239.png)

**Comment by csbduzi** [comment]
Acceptance Test PASS: 

![screen shot 2019-03-06 at 6 29 02 pm](https://user-images.githubusercontent.com/46238950/53921332-0060ba80-403e-11e9-828b-e3b48448537f.png)
