### ISSUE TITLE
OpenDialog Not closing issue 

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#114]
After implementing the openDialog, everything was showing correctly. However, I can't close the window by pressing anywhere one the tab. This is referred to commit  #113. It is a critical bug because the user won't be able to do anything unless close the whole tab and open it again.

**Comment by Hambrsoom** [comment]
Are we still having this issue ? @CarenRizk

**Comment by CarenRizk** [comment]
This bug has been fixed, one of the options that were added by mistake to the dialog is to disable it from closing when clicking outside. Removing this option fixed the bug
