### ISSUE TITLE
Deleting a Wit

### ISSUE THREAD

**Issue by mohanadarafe** [mohanadarafe/s341-witwit#129]
User should be able to delete a wit once its been posted.

**Comment by mohanadarafe** [comment]
Deleting wit now functional.

**Comment by csbduzi** [comment]
Acceptance Test PASS:

![screen shot 2019-03-06 at 6 21 34 pm](https://user-images.githubusercontent.com/46238950/53920955-d65ac880-403c-11e9-92dc-b6e55e4a8507.png)
