### ISSUE TITLE
User may not delete a Wit that is not his

### ISSUE THREAD

**Issue by mohanadarafe** [mohanadarafe/s341-witwit#131]
Currently, a user can delete ANY wit. We want to ensure that the user may only delete wits that are his.

**Comment by Hambrsoom** [comment]
This is considered more as a bug. That's why i changed the label.

**Comment by Hambrsoom** [comment]
Problem solved :). User can only delete their own wits now.
As shown in the below picture, the Garbage can is only on the wits of the user who is logged in.

![image](https://user-images.githubusercontent.com/32947679/53385936-302d0580-394e-11e9-9f4b-13d0acd5ef7a.png)
