### ISSUE TITLE
User can add a comment on any wit. 

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#135]
The user can comment on any wit either if he/she is following the user who posted the wit or no. Refer to feature #38 

**Difficulty Level** = 2/5
**Priority Level** = HIGH

**Comment by Hambrsoom** [comment]
Completed as well. and working perfectly

**Comment by bernzclav** [comment]
Acceptance Test - Comment

![image](https://user-images.githubusercontent.com/37311291/54884211-953c2400-4e44-11e9-8a84-d5ff93c82387.png)
