### ISSUE TITLE
User can edit his comment in a wit. 

### ISSUE THREAD

**Issue by AlainJobs** [mohanadarafe/s341-witwit#136]
After submitting a comment, a user should be able to edit his previous input. #38 

Difficulty Level = 2/5
Priority Level = Medium

**Comment by Hambrsoom** [comment]
the user has been implemented. The user will have textArea which contains the previous reply and they can edit it and resubmit it 
![image](https://user-images.githubusercontent.com/32947679/54872900-28704d80-4da2-11e9-96bd-c3b76a6562a8.png)

![image](https://user-images.githubusercontent.com/32947679/54872908-332ae280-4da2-11e9-8155-9947549adb8e.png)

**Comment by DariushN** [comment]
Acceptance test: User can edit his reply on wit
Result: PASSED
<img width="635" alt="Screen Shot 2019-03-25 at 5 15 45 PM" src="https://user-images.githubusercontent.com/35940376/54954713-a9098800-4f21-11e9-8eb7-e22ac37dff96.png">
