### ISSUE TITLE
The user would see the most recent comment at the bottom. 

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#139]
When the user adds a new comment, it will be added at the bottom of the list of comments.  Refer to feature #38.

**Comment by Hambrsoom** [comment]
Regarding the order, we have implemented it in a way that is similar to twiter where the new replies will be posted at the end. 
![image](https://user-images.githubusercontent.com/32947679/53685779-37a53380-3ced-11e9-8710-79b9ab026aec.png)
we can see that when we check up the time on the right side of every reply.

**Comment by HussainWitwit** [comment]
<img width="1099" alt="Screen Shot 2019-03-23 at 7 09 06 PM" src="https://user-images.githubusercontent.com/40703467/54872729-2bb60a00-4d9f-11e9-9b35-fe443f9a51e7.png">
