### ISSUE TITLE
User can register.

### ISSUE THREAD

**Issue by csbduzi** [mohanadarafe/s341-witwit#14]
Users should be able to register by entering their name, email address and password.

**Comment by Hambrsoom** [comment]
It is necessary to execute this test case with the backend and after connecting the frontend with the backend.

**Comment by AlainJobs** [comment]
The user shouldn't be able to input a username separated by a space. So far, we didn't encounter any bugs regarding that situation, but it might lead to bugs in the future.

**Comment by Hambrsoom** [comment]
Alain, I have tested your case and it worked correctly without any problems. Also, i did some simple testing regarding it and everything was working good.

**Comment by csbduzi** [comment]
User Story: A user will be able to register through this page. The user will have to input his information through out these input forms: username, password, email, age, and sex. Once, the user has finished, he can press on the register button and an account will be created for him.

**Comment by HussainWitwit** [comment]
Acceptance Test - Register
Risk leve = 5/5
Priority level = HIGH
Story Points (Effort Estimation) = 5/5
<img width="1153" alt="Screen Shot 2019-03-23 at 5 01 56 PM" src="https://user-images.githubusercontent.com/40703467/54871649-12f12880-4d8e-11e9-8617-adb813a59a4e.png">
