### ISSUE TITLE
Functional edit button in a reply. 

### ISSUE THREAD

**Issue by AlainJobs** [mohanadarafe/s341-witwit#147]
Add an edit button on every comment that the user posted. Once it's clicked, the same textbox should be reopened to change modify the text without duplication of the comment.
Related to user story #136

**Comment by Hambrsoom** [comment]
@mohanadarafe and @CarenRizk  did a great job in completing this.

![image](https://user-images.githubusercontent.com/32947679/54873098-e21ced80-4da5-11e9-87de-3cf70fb7a9bc.png)
