### ISSUE TITLE
User can login in.

### ISSUE THREAD

**Issue by csbduzi** [mohanadarafe/s341-witwit#15]
Logging in to an existing account will require the user to enter his username (or email address) and his password.

**Comment by Hambrsoom** [comment]
Same as the register case. It is necessary to test it before connecting the backend with the frontend and after doing so.

**Comment by Hambrsoom** [comment]
The testing for the login is completed. And everything is working correctly. Therefore, The task for login is ready to ship for sprint 1.

**Comment by DariushN** [comment]
UserStory: The user will be able to log into his account using the login page. Once the user will submit his username and password through the form, he will be able to sign into and access his account

**Comment by HussainWitwit** [comment]
Risk level = 5/5
Priority level = HIGH
Story Points (Effort Estimation) level = 4.25/5
<img width="1043" alt="Screen Shot 2019-03-23 at 5 40 13 PM" src="https://user-images.githubusercontent.com/40703467/54871971-1fc44b00-4d93-11e9-9b28-46e00d82b204.png">
