### ISSUE TITLE
Provide the time 

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#150]
Showing the time when the reply was posted on the right side of the reply just like it is shown on the wits. Also, for the backend make sure that the timestamp column exists on the replies table in the database. user Story #140

**Comment by csbduzi** [comment]
@Hambrsoom and @CarenRizk are guys on this task already?

**Comment by Hambrsoom** [comment]
yes, and it is already implemented as you can see in the below picture:

![image](https://user-images.githubusercontent.com/32947679/53685741-a8981b80-3cec-11e9-9bb2-a24244e11f79.png)
