### ISSUE TITLE
Implement acceptance test for every commit.

### ISSUE THREAD

**Issue by AlainJobs** [mohanadarafe/s341-witwit#154]
Concerning this automation testing: 
We already have the acceptance that supports our commits, however, it is not yet implemented. Every commits, even the ones prior to this sprint should pass through the acceptance test. So far, every commit has an X done by Travis-Ci (implemented by @mohanadarafe ).

**Comment by Hambrsoom** [comment]
How is this going  ?  It must be done asap

**Comment by csbduzi** [comment]
It's complete! All core features and their user stories have successfully passed the Acceptance Test! Screenshots of the reports can be found under each user story issues. @AlainJobs @Hambrsoom
