### ISSUE TITLE
Search for profile

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#155]
This feature is a combination between users having profile and accessing other people's profile through the search engine.

**Risk** level  = 3.5/5
**Priority** level = HIGH
**Story Points (Effort Estimation)** level = 4/5

**Comment by DariushN** [comment]
Users are now able to search for users using the searchbar and go to their profile by pressing on the "Go to profile" icon as show below on the search result cards
<img width="1118" alt="Screen Shot 2019-03-26 at 5 59 41 PM" src="https://user-images.githubusercontent.com/35940376/55036418-f6085f80-4ff0-11e9-9ecb-56bf511e57dc.png">

**Comment by DariushN** [comment]
Users also have individual profiles that can be accessed by any other users signed in to the website. The picture below shows an exterior view of a profile (user other than the one being shown accesses it) 
<img width="1266" alt="Screen Shot 2019-03-26 at 6 03 57 PM" src="https://user-images.githubusercontent.com/35940376/55036680-c0b04180-4ff1-11e9-9339-1c6da300e2e9.png">

**Comment by Hambrsoom** [comment]
It looks good :3
