### ISSUE TITLE
User can follow the followers of their followers.

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#157]
The user has the right to see other people's followers to follow them too. User story for  the feature #107 .

**Comment by Hambrsoom** [comment]
This feature has been completed in combination between the searching for users and the list that's given at the following tab in the profile of the user.

**Comment by Hambrsoom** [comment]
The functionality of these two features have been already described in the the divided tasks.

**Comment by DariushN** [comment]
Acceptance test : Follow followers of followers
Result: PASS
<img width="350" alt="Screen Shot 2019-03-25 at 4 44 01 PM" src="https://user-images.githubusercontent.com/35940376/54952849-54640e00-4f1d-11e9-8deb-6c99dc86573e.png">
