### ISSUE TITLE
User can edit personnal info.

### ISSUE THREAD

**Issue by AlainJobs** [mohanadarafe/s341-witwit#158]
The user should be able to edit his personal info (the same as the one in the registration page).
Related to user story #71 

**Risk** level  = 3.5/5
**Priority** level = MEDIUM
**Story Points (Effort Estimation)** level = 3.5/5

**Comment by RobertBeaudenon** [comment]
I see that two other issues are related to this one #161 and #163 (which is the front end and the backend). So i'm not sure what i need to work on. Can anyone clarify.

**Comment by csbduzi** [comment]
Hey @RobertBeaudenon ,

You and I can work on the backend if you want, the front-end is literally finished.

CSB

**Comment by csbduzi** [comment]
@AlainJobs has an exam Saturday so I doubt he will have time

**Comment by Hambrsoom** [comment]
@csbduzi  has implemented the front and backend for editing the personal information of a user:

![image](https://user-images.githubusercontent.com/32947679/54872940-a3396880-4da2-11e9-9171-f3b04bcca5ea.png)

In addition, he added the ability to reset the password.
