### ISSUE TITLE
User can show the posts which they liked 

### ISSUE THREAD

**Issue by AlainJobs** [mohanadarafe/s341-witwit#159]
To share it with other users, the user wants to share what he liked with other people #157 and the feature #155 

**Risk** level  = 3/5
**Priority** level = MEDIUM
**Story Points (Effort Estimation)** level = 3.5/5

**Comment by Hambrsoom** [comment]
We implemented this story by adding a tab for likes which shows the wits that has been liked by the user.

![image](https://user-images.githubusercontent.com/32947679/54872972-5b671100-4da3-11e9-86f7-20705e89ef08.png)
