### ISSUE TITLE
Functional Edit info button -- > front-end

### ISSUE THREAD

**Issue by AlainJobs** [mohanadarafe/s341-witwit#161]
Add an edit info button on the profile page of each user. When going to his profile, clicking this button would allow him to override the information he inputted during the registration phase. Front-end only, i.e focus on adapting the user interface for override info.

Related to sub user story #158

**Comment by csbduzi** [comment]
Hey Alain,

The front end of the edit profile button has been implemented. Here is a look : 

![Screen Shot 2019-03-14 at 10 55 00 PM](https://user-images.githubusercontent.com/46238950/54405690-d480ad00-46ad-11e9-9f28-f7fed8b80254.png)
