### ISSUE TITLE
Functional edit button --> Back-end

### ISSUE THREAD

**Issue by AlainJobs** [mohanadarafe/s341-witwit#163]
Update the backend with the newly changed values.

_Suggestions_ : Might take a look at the registration modules to understand how they did or simply re-call their functions in your code.

Related to sub user story #158

**Comment by csbduzi** [comment]
Hey Alain,

The back-end for the edit profile button has been implemented. 
Now its only question of testing it for all possible cases, which I'm doing right now :)

CSB
