### ISSUE TITLE
Suggested should have suggestion upon searching profiles.

### ISSUE THREAD

**Issue by AlainJobs** [mohanadarafe/s341-witwit#165]
Upon searching a user in the search bar, suggestions should appear. 
Related to user story #73 

**Risk** level  = 3.5/5
**Priority** level = MEDIUM
**Story Points (Effort Estimation)** level = 4/5

**Comment by Hambrsoom** [comment]
@DariushN  can u push what u have done so we can test it ?

**Comment by DariushN** [comment]
@Hambrsoom Pushed it and now merged! :)

**Comment by bernzclav** [comment]
Dropdown list implemented suggesting users to search as the user searching types in characters. This results in a dynamic search.

![image](https://user-images.githubusercontent.com/37311291/55122430-5ec90800-50d5-11e9-97f8-9f1348f36aaa.png)
