### ISSUE TITLE
Implement dropdown list for suggested users

### ISSUE THREAD

**Issue by AlainJobs** [mohanadarafe/s341-witwit#167]
This could be implemented in various types of ways. 
_Suggestions:_  
- match the string inserted with the name of the users in the database!?
- look at bootstrap lib, there are a lot of resources for suggested search bars.
Related to sub-user story #165

**Comment by bernzclav** [comment]
As a user types characters in the search bar, suggested users will appear. If the user selects a suggested user to search, its name will then be added in the search bar. The user can then proceed to search.

![image](https://user-images.githubusercontent.com/37311291/55122317-da768500-50d4-11e9-93ea-6e706ebc1851.png)
