### ISSUE TITLE
Database Arrangement 

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#20]
- Figuring out how many tables we need. 
- What will be stored in each table.
- Which tables will be connected together 
**It will be nice to have a visualisation for the database design.

**Comment by mohanadarafe** [comment]
Any updates on this Hambrsoom?

**Comment by Hambrsoom** [comment]
Yes, at the beginning of sprint 2, i will provide you with an image to better visualize it

**Comment by Hambrsoom** [comment]
I finally finished arranging the database and it is working correctly. 
I have added a picture for the design, a .txt file for the sql and a dump file so everyone case use it from their local laptops.
