### ISSUE TITLE
Every user should have a profile 

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#216]
Every user should have their own profile to be accessed by the user logged in  #155 

**Risk** level  = 3.5/5
**Priority** level = HIGH
**Story Points (Effort Estimation)** level = 4/5

**Comment by bernzclav** [comment]
Acceptance Test - Profile: PASSED

![image](https://user-images.githubusercontent.com/37311291/54884540-cf0f2980-4e48-11e9-8dbb-e68a1b200e2d.png)
