### ISSUE TITLE
user should see their activities on their profile

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#219]
The user would be able to see their own stuff on their profile 

**Risk** level  = 2.5/5
**Priority** level = HIGH
**Story Points (Effort Estimation)** level = 2/5

**Comment by DariushN** [comment]
Acceptance test: User should see their activities on their profile
Result: PASSED
<img width="710" alt="Screen Shot 2019-03-25 at 4 54 24 PM" src="https://user-images.githubusercontent.com/35940376/54953476-b07b6200-4f1e-11e9-8a5e-8d7f4e2c5c24.png">

**Comment by DariushN** [comment]
The user is able to look at his activities simply by pressing the Profile tab.
User has to click a sub-tab to filter the activities, for example to show only Wit activities

<img width="1084" alt="Screen Shot 2019-03-25 at 5 05 29 PM" src="https://user-images.githubusercontent.com/35940376/54954174-6d21f300-4f20-11e9-96a1-7b864f7f0c53.png">
