### ISSUE TITLE
Implenting the backend for wits profile

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#221]
We need to provide the frontend with the required information to show the wits they liked and their own wits.

**Comment by RobertBeaudenon** [comment]
I think i already implemented that in issue #103

**Comment by Hambrsoom** [comment]
this is should be implemented for the others' profile and not on the one of my profile.

**Comment by Hambrsoom** [comment]
This has been implemented and functioning correctly for different users profile. It is also connected to the frontend.
