### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by RobertBeaudenon** [mohanadarafe/s341-witwit#254]
We will follow the guidelines from this page : https://github.com/felixge/node-style-guide#use-uppercase-for-constants

**Comment by Hambrsoom** [comment]
For the backend: The routes will look like this : 
![image](https://user-images.githubusercontent.com/32947679/54869100-5639a000-4d6a-11e9-9034-e3e0bed05755.png)


![image](https://user-images.githubusercontent.com/32947679/54869103-5cc81780-4d6a-11e9-8be6-4a2233194c08.png)

**Comment by Hambrsoom** [comment]
In addition for the frontend: 

![image](https://user-images.githubusercontent.com/32947679/55125298-a5bbfb00-50df-11e9-8636-4dc679ae2d55.png)
This is the template to follow for methods:
![image](https://user-images.githubusercontent.com/32947679/55125345-cc7a3180-50df-11e9-8e3c-c8bbafd2f4b7.png)

**Comment by Hambrsoom** [comment]
For both frontend and backend --> the const variables have capital letters
