### ISSUE TITLE
Forgot my Password page

### ISSUE THREAD

**Issue by mohanadarafe** [mohanadarafe/s341-witwit#30]
Let's get the forget my password done, use PHP-Mailer in order to send the client the info they need to recover their password. Have a look: https://github.com/PHPMailer/PHPMailer

I have used it in the past, if you need help with it let me know!

**Comment by csbduzi** [comment]
Reminder : to put a restriction on the text field input.

The user should enter a valid email. If the entered input is not a valid email, an error message should show up.

**Comment by csbduzi** [comment]
UserStory: The forget-password page is a page that the user can use if he wants to recover his forgotten password. Once, the user is on the forget-password page, he can enter his email in the input form and press on the "submit" button. Once the user has pressed on the button, an email will be sent to the user's email. In the email, the user will found that his password has been sent back to him.

**Comment by Hambrsoom** [comment]
This feature will be finished in sprint 2.

**Comment by Hambrsoom** [comment]
This feature is done too. However, there is a new issue which is an enhancement that Alain is working on it.

**Comment by csbduzi** [comment]
Risk leve = 2/5
Priority level = HIGH
Story Points (Effort Estimation) level = 3

**Comment by csbduzi** [comment]
Acceptance Test:

![Screen Shot 2019-04-08 at 4 25 40 PM](https://user-images.githubusercontent.com/46238950/55754600-0c63e180-5a1b-11e9-9e11-fc48ca0fd625.png)
