### ISSUE TITLE
The age is crashing the whole database when signing up. 

### ISSUE THREAD

**Issue by AlainJobs** [mohanadarafe/s341-witwit#31]
**_Possible solution:_** Hampic's database is expecting a number (I think an integer), but your age is sending a data of type 'date'. Maybe converting that date to a number would fix the issue.

**Comment by mohanadarafe** [comment]
Change the input type in register.specs.html to NUMBER. If that does not work maybe you can CAST in SQL a string->number

**Comment by RobertBeaudenon** [comment]
I told Mohanad already, Bernard changed the age input field as in "birthday date" that's why its not working. We need to extract the age from he birthday date then pass it to the database. This might be done using JavaScript i think.

**Comment by AlainJobs** [comment]
Okay, I'll try to consolidate that with Hampic during my next meeting with him

**Comment by bernzclav** [comment]
Changed age input type from "date" back to "number". We had decided to put "date" on Friday but it did indeed create too many issues with the back end. 
This issue is now closed.
