### ISSUE TITLE
Enhance/Consolidate back end with updated form validation.

### ISSUE THREAD

**Issue by AlainJobs** [mohanadarafe/s341-witwit#34]
I upgraded the form validation with all the red rectangles and the messages for required inputs. However, we will need to adjust the way the database gets the information. Shouldn't be hard. Me and Hampic will work on that at our next meeting. Cheers #tontonAlain

**Comment by Hambrsoom** [comment]
So, this feature is working for the register part. I opened an enhancement for the login and forget password that is related to this subject. We will start working on it asap. Cheers Hambrsoom.
