### ISSUE TITLE
#UserStory // The user can register.

### ISSUE THREAD

**Issue by AlainJobs** [mohanadarafe/s341-witwit#35]
The user can sign up to the website.

**Comment by AlainJobs** [comment]
This issue was already posted days ago. Sorry for the repost. We cannot delete issues io GitHub (surprisingly).

**Comment by HussainWitwit** [comment]
Same test to issue #14 (same issue)
<img width="1153" alt="Screen Shot 2019-03-23 at 5 01 56 PM" src="https://user-images.githubusercontent.com/40703467/54871660-46cc4e00-4d8e-11e9-92a1-f2edcb96a4c9.png">
