### ISSUE TITLE
Post a Wit

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#36]
The user would be able to post a wit.

**Comment by Hambrsoom** [comment]
Regarding this user story, we have got the user to be able to post a new wit and show it on the timeline.  
![image](https://user-images.githubusercontent.com/32947679/52648582-c70cb300-2eb4-11e9-9d07-da14e6090f9f.png)

**Comment by Hambrsoom** [comment]
#48 represents the implementation of the backend for timeline showing wits and #57 is for posting the wits and connecting the backend to the frontend.

**Comment by CarenRizk** [comment]
Posting with feedback is done

**Comment by csbduzi** [comment]
Acceptance Test PASS: 

![screen shot 2019-03-06 at 6 06 52 pm](https://user-images.githubusercontent.com/46238950/53920363-e671a880-403a-11e9-99c4-cf5a34ec65fa.png)
