### ISSUE TITLE
Like a Wit

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#37]
Core Feature 2: The user would be able to like a wit.

**Comment by RobertBeaudenon** [comment]
Should i wait first that the issue "post a wit" is completed to start that

**Comment by Hambrsoom** [comment]
As you can see @RobertBeaudenon Posting a wit has been completed. However, we are adjusting some stuff regarding it.  The liking is in the process to work as well. The below pictures demonstrates the design of wits showing on the timeline. 
![image](https://user-images.githubusercontent.com/32947679/52649004-7a75a780-2eb5-11e9-958d-64f329c832a1.png)

**Comment by CarenRizk** [comment]
user can like a wit is implemented and connected with backend, although related issues are being worked on right now.

**Comment by Hambrsoom** [comment]
So, this core feature is also done.,
