### ISSUE TITLE
Set up and use TravisCI as testing software 

### ISSUE THREAD

**Issue by csbduzi** [mohanadarafe/s341-witwit#42]
Show CI works and have empty tests available in the Sprint 2

- slide 18 in PowerPoint week3_devops

**Comment by Hambrsoom** [comment]
Is everything going well for the implementation of TravisCI?

**Comment by csbduzi** [comment]
TravisCI has to be initially set up by the owner of the repo. I have asked @mohanadarafe to enable the hook since he's the owner of the repo. He will get back to us.

**Comment by Hambrsoom** [comment]
@mohanadarafe Do you have any updates regarding this ?

**Comment by mohanadarafe** [comment]
Check the Travis branch, I posted the .travis.yml file and it is up and running.

**Comment by Hambrsoom** [comment]
Perfect 💯
