### ISSUE TITLE
Required tag for the login and forget password frontend

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#43]
The login and forget password are working correctly at the moment. However, it would be nice if we have a verification of filling up the fields just like the register one.

**Comment by AlainJobs** [comment]
Consider it done!

**Comment by Hambrsoom** [comment]
I like that

**Comment by Hambrsoom** [comment]
I will help u with it for the backend and making sure that it is working all the way from the frontend to the database.
