### ISSUE TITLE
Showing the user info

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#51]
On the timeline, we need to have the user info shown in a box on the top left corner. (User picture, how many followers, followings and posts). These information should be retrieved from be asked from the backend where @RobertBeaudenon  will be taking care of.

**Comment by Hambrsoom** [comment]
Regarding about showing the user info on the timeline. Can u update us of its status ?

**Comment by bernzclav** [comment]
This is done. As of right now, a user can see his or her name, age, number of following and followers on his timeline. 

![witwituserinfo](https://user-images.githubusercontent.com/37311291/52730439-56839600-2f89-11e9-9461-f5f198bcbeb5.png)
