### ISSUE TITLE
Showing the wits on the timeline.

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#53]
The timeline should contains a specific number of wits and having a button on which the user can press to see older wits. Each wit should show the post itself, written by who and number of likes.  I shall be taking care of the backend of this process. #77

**Comment by mohanadarafe** [comment]
So, we set a limit of wits when originally loaded & add buttons to show more or refresh wits? 

When you say back-end part are You referring to the wit showing up on the TL when someone presses on “Post”?

**Comment by Hambrsoom** [comment]
having a button that says shows older in case if the user wants to see more and older wits. I will send all the wits to the frontend and it is your responsability to manage it and display it on the timeline. and no no. The posting part it will be added automatically to the timeline by automatically refreshing the page.

**Comment by Hambrsoom** [comment]
As we can see the timeline looks way better now. We have a nice timeline now where on the top we have a place for posting as shown in the below picture:

![image](https://user-images.githubusercontent.com/32947679/52730238-e5dc7980-2f88-11e9-9000-52a7067f351d.png)

and for the posts are shown like this: 

![image](https://user-images.githubusercontent.com/32947679/52730305-0c021980-2f89-11e9-9a51-e42aef540028.png)
