### ISSUE TITLE
Allowing the user to upload an image when registering

### ISSUE THREAD

**Issue by RobertBeaudenon** [mohanadarafe/s341-witwit#59]
We need to add a field where the user can upload an image in the registration tab,
The image will be required to create the account.

**Comment by Hambrsoom** [comment]
Any progress regarding this issue  ?

**Comment by mohanadarafe** [comment]
Master branch updates:
- Registration page contains upload photo option
- Image folder where user must put pictures in (relative path)

What is missing:
- Using path variable in other pages

**Comment by Hambrsoom** [comment]
We need to find a way to store a copy of the image on the server side.

**Comment by mohanadarafe** [comment]
Any updates on this? @AlainJobs

**Comment by Hambrsoom** [comment]
After long researches. Alain and me were able to implement this part yesterday. Now, the user can upload a picture :)

**Comment by AlainJobs** [comment]
This can be considered as a user story as well since it's something the user can do while using the app.

**Comment by AlainJobs** [comment]
Since as user story, it would require an acceptance test, we will keep it as nonstory tasks.
