### ISSUE TITLE
Allowing users to register with the same email

### ISSUE THREAD

**Issue by mohanadarafe** [mohanadarafe/s341-witwit#64]
We must make sure that emails & user name is unique. Try to create two users with the same e-mail it will not work.

**Comment by csbduzi** [comment]
Scenarios that needed to be handled for the register page

Case 1: Username Taken: user enters an username that already exists in the database

![screen shot 2019-02-13 at 11 12 12 pm](https://user-images.githubusercontent.com/46238950/52762284-ef93ca80-2fe4-11e9-9577-e2b7051a3c6a.png)


Case 2: Email Taken: user enters an email that is already associated with an existing user in the database 

![screen shot 2019-02-13 at 11 12 35 pm](https://user-images.githubusercontent.com/46238950/52762291-fa4e5f80-2fe4-11e9-8d46-685891f922d7.png)
