### ISSUE TITLE
User should be able to follow other people 

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#70]
Relating to one our core features. The user should be able to follow the people in order to see their wits on the timeline. 
#107

**Comment by AlainJobs** [comment]
User Story related to #107 .

**Comment by Hambrsoom** [comment]
this is technically is completed. Where the user can search people to follow

**Comment by csbduzi** [comment]
Acceptance Test PASS:

![screen shot 2019-03-06 at 6 16 04 pm](https://user-images.githubusercontent.com/46238950/53920704-fdfd6100-403b-11e9-8027-8fe986486dfc.png)
