### ISSUE TITLE
User should have the opportunity to search for people to follow 

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#71]
the user will be able to search for other users in order to follow them. This one is related to the feature #155 .

**Risk** level  = 3.5/5
**Priority** level = HIGH
**Story Points (Effort Estimation)** level = 3/5

**Comment by daphneaugier** [comment]
Template almost done

**Comment by HussainWitwit** [comment]
<img width="1210" alt="screen shot 2019-02-17 at 5 16 01 pm" src="https://user-images.githubusercontent.com/40703467/52920289-e6527880-32d8-11e9-85e1-51352bf2b0e1.png">

This is what we have presently, we will modify some features such as the follow/unfollow button!

**Comment by RobertBeaudenon** [comment]
To populate the wits on the profile :
1- I created the' services ' Folder in profile with the required files.
2-The Array of object 'userWits' can be directly used in the Html body to retrieve the wits.
3- I am also getting the Number of Likes for each userWit accessible with 'likesListProfile'

**Comment by mohanadarafe** [comment]
Updated the profile front-end with fetched data from DB
<img width="1355" alt="07e41a83842b364241611fd99aa605d1" src="https://user-images.githubusercontent.com/34899555/53190700-2155f400-35d8-11e9-9318-ecb75bc3f5df.png">

**Comment by HussainWitwit** [comment]
<img width="1098" alt="Screen Shot 2019-03-27 at 9 42 24 PM" src="https://user-images.githubusercontent.com/40703467/55123552-71454080-50d9-11e9-9797-2a5659ca2d40.png">
