### ISSUE TITLE
The user would have the opportunity to unfollow people

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#72]
The user would have the opportunity to unfollow the people whom he/she doesn't want to follow anymore.   feature #107 

**Difficulty** Level  = 1/5 Once the following is done.
**Priority** Level = HIGH

**Comment by Hambrsoom** [comment]
The backend has been implemented. We are waiting for the frontend. which will be implemented by @CarenRizk

**Comment by Hambrsoom** [comment]
Because we have a dynamic button, when the user search for someone, they have followed. they will have the button which says to unfollow and follow button if the user isnot following that user

**Comment by csbduzi** [comment]
Acceptance Test PASS: 

![screen shot 2019-03-06 at 6 16 55 pm](https://user-images.githubusercontent.com/46238950/53920741-1cfbf300-403c-11e9-9071-48e1e0923f6e.png)
