### ISSUE TITLE
The user can search for people whom he/she wants to follow

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#73]
The user should have the ability to search for some specific people in case if they want to follow them. This is considered as a user story for feature #155

**Comment by DariushN** [comment]
Logged in users are now able to search for other profiles through their usernames. Now waiting for individual profiles pages to be created and for profile pictures feature to be finished in order to complete it.

**Comment by Hambrsoom** [comment]
Why are you waiting for these two features ?? what do you have in mind ?

**Comment by DariushN** [comment]
Hi Hambrsoom, I'm waiting for these features so that I can display the user image to their profile search card, and also link their search cards to the user's profile page

**Comment by DariushN** [comment]
For now, I have replaced the image by a default Ryan Gosling profile picture, and created a button that will eventually be linked to the profile page of the user searched for.

**Comment by DariushN** [comment]
![image](https://user-images.githubusercontent.com/35940376/53689013-684f9200-3d1a-11e9-8c15-0336e0a321c4.png)
This is what a search card looks like for the moment. Will need to add user image and link this card to the user profile later on (probably next sprint).
