### ISSUE TITLE
The user needs to be informed about the success of posting their wit

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#74]
The user should be informed by a friendly message that their post has successfully posted and been able to see it on the timeline directly. This is a user story for feature #36 .

**Comment by CarenRizk** [comment]
used snackbar service to implement this

**Comment by csbduzi** [comment]
Acceptance Test PASS:

![screen shot 2019-03-06 at 6 12 44 pm](https://user-images.githubusercontent.com/46238950/53920581-a101ab00-403b-11e9-938f-eef0c60f609a.png)
