### ISSUE TITLE
User should be able to unlike a wit

### ISSUE THREAD

**Issue by bernzclav** [mohanadarafe/s341-witwit#76]
The User should be able to unlike a wit he or she has previously liked. This should be done by clicking on an unlike button, immediately reverting the wit to its original state. 

This is a user story for Feature #81  .

**Comment by Hambrsoom** [comment]
So, for this, we have one button where the user can use to like or unlike.
If the user didn't like a post: they will see a full heart --> they can like it 
![image](https://user-images.githubusercontent.com/32947679/52730774-2ab4e000-2f8a-11e9-8c43-2b01861bb9a2.png)
if the user already like a post: they will see a broken heart --> they can unlike it:

![image](https://user-images.githubusercontent.com/32947679/52730814-428c6400-2f8a-11e9-8791-6dca17804d5a.png)
