### ISSUE TITLE
The user can see the most recent wits first

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#77]
The user should be able to see the wits in chronological order from the recent one to the oldest. This related to #36.

**Comment by CarenRizk** [comment]
@mohanadarafe and me reversed the array of wits that we're getting from the backend since we're getting it already sorted but from oldest to newest post..now it's from newest to oldest

**Comment by HussainWitwit** [comment]
Risk level = 2/5
Priority level = HIGH
Story Points (Effort Estimation) level = 1/5
<img width="999" alt="Screen Shot 2019-03-27 at 9 29 58 PM" src="https://user-images.githubusercontent.com/40703467/55123085-a0f34900-50d7-11e9-8563-feeae5d54a8c.png">
