### ISSUE TITLE
The user would be able to see the time for each wit

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#78]
The user should be able to see the wits in chronological order. Also, they should see the date when this wit was posted. This is related to #77

**Comment by CarenRizk** [comment]
used moment.js to implement. If the wit has been posted less than a day ago we show a fromNow instance, ex: "6 hours ago, couple of seconds ago". If the post has been posted more than a day it shows the date, ex: "February 6th 2019".
