### ISSUE TITLE
The user needs to know about the validation of their wit before posting.

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#80]
The user's wit should be validated before posting it on the timeline. This is related to #36.

**Comment by Hambrsoom** [comment]
Can you elaborate more about the implementation of this part? @CarenRizk

**Comment by CarenRizk** [comment]
If the wit textArea is empty the post button will be disabled. Furthermore, the max input is 100 characters, the user can't type more than 100 characters in the text area.
