### ISSUE TITLE
User should be able to like a wit from people they are following

### ISSUE THREAD

**Issue by bernzclav** [mohanadarafe/s341-witwit#81]
The User should be able to like a wit from the people they are following through the user timeline. 

This is a user story for Feature #37 .

**Comment by Hambrsoom** [comment]
Completely functional.

**Comment by csbduzi** [comment]
Acceptance Test PASS:

![screen shot 2019-03-06 at 5 56 49 pm](https://user-images.githubusercontent.com/46238950/53920245-795e1300-403a-11e9-885b-716277c545d2.png)
