### ISSUE TITLE
User can like a wit from a user that he is not following

### ISSUE THREAD

**Issue by bernzclav** [mohanadarafe/s341-witwit#83]
User should be able to like a wit from a user that he is not following, and thus a wit that is not showing on his own timeline. 

This is a user story for Feature #37 .

**Comment by RobertBeaudenon** [comment]
The only way of liking a wit from a user that he is not following is by going on is profile?

**Comment by csbduzi** [comment]
Yes, because otherwise the wit would be found on the timeline of logged in user.

**Comment by csbduzi** [comment]
I don't think there will be another way of accessing wits of users that your not following.

**Comment by Hambrsoom** [comment]
For the moment, we made the timeline public where the user can see the wits of the users, the user is following or not.

**Comment by HussainWitwit** [comment]
Risk leve = 2/5
Priority level = LOW
Story Points (Effort Estimation) level = 1/5
<img width="1014" alt="Screen Shot 2019-03-27 at 9 17 23 PM" src="https://user-images.githubusercontent.com/40703467/55122594-e151c780-50d5-11e9-9476-424933932c93.png">
