### ISSUE TITLE
Adding button for like/unlike 

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#87]
At the tile of each post, the user should see two buttons: one for liking a wit and one for unliking the post. This is implemented on the timeline. #81

**Comment by Hambrsoom** [comment]
Make sure the user can only like a wit once. Also, they can unlike it once if they have already liked it before.

**Comment by CarenRizk** [comment]
It should be one buuton when the user likes a wit the button will be solid (filled with color) if the user clicks a solid heart the post will be unliked

**Comment by Hambrsoom** [comment]
so it looks something like this 
![image](https://user-images.githubusercontent.com/32947679/52686295-0a017180-2f1b-11e9-951a-38982d9c7d95.png) to like and 

![image](https://user-images.githubusercontent.com/32947679/52686314-18e82400-2f1b-11e9-9f2f-167301fc797b.png)
to unlike

**Comment by Hambrsoom** [comment]
The two of them were implemented as one bottom: The like button will appear in case if the user didn't like the post otherwise, the other one will appear.
