### ISSUE TITLE
Showing the list of likes

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#88]
The user should be able to see people's names who liked a wit.Implementing the tooltip that will pop up and contains the names of the people who liked the post. User Stroy #79

**Comment by Hambrsoom** [comment]
Implementing the tooltip that will pop up and contains the names of the people who liked the post.

**Comment by Hambrsoom** [comment]
i have just finished implementing this part; at commit #112 and #115 . Also, @CarenRizk Helped to make fix my code and make it look nicer. The design looks like this:

![image](https://user-images.githubusercontent.com/32947679/52733250-415e3580-2f90-11e9-9832-bf1822e5d482.png)

**Comment by csbduzi** [comment]
Acceptance TEST PASS:

![screen shot 2019-03-06 at 6 39 03 pm](https://user-images.githubusercontent.com/46238950/53921624-25096200-403f-11e9-8149-398e8697f854.png)
