### ISSUE TITLE
Small pop for posting problem

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#91]
The user should receive a pop up that says that he isn't able to post the wit because the post is empty or because the post is way too long. #75

**Comment by Hambrsoom** [comment]
So, technically the user won't be able to post a wit unless he writes something.

**Comment by mohanadarafe** [comment]
The post button has been disabled when the text box is empty.

![52300351_336050587012655_4760913875442860032_n](https://user-images.githubusercontent.com/34899555/52733430-b467ac00-2f90-11e9-9d95-6d1d82dfa220.png)
