### ISSUE TITLE
Showing the time

### ISSUE THREAD

**Issue by Hambrsoom** [mohanadarafe/s341-witwit#92]
At right edge of each tile for each wit, there should be the date at which time the wit was posted.  Related to #78 .

**Comment by Hambrsoom** [comment]
time is shown beside each post such as the picture below:

![image](https://user-images.githubusercontent.com/32947679/52734629-b97a2a80-2f93-11e9-8bb2-594a1afb87c7.png)

**Comment by mohanadarafe** [comment]
Hi Hambrsoom,

This feature is already done, as you can see when you post a wit, it shows it has been posted a few seconds ago.
![51856709_250177782567616_6564546221296320512_n](https://user-images.githubusercontent.com/34899555/52752901-7e432000-2fc2-11e9-91c1-1fc256169580.png)
