### ISSUE TITLE
User has tab on profil with all his/her liked wits

### ISSUE THREAD

**Issue by daphneaugier** [mohanadarafe/s341-witwit#93]
When on profile, user is automatically seeing the Wit posted. However, there is a tab where user can see the wits he/she likes. This is showed as a timeline.

**Comment by Hambrsoom** [comment]
How is it guys going ?

**Comment by daphneaugier** [comment]
I will add the toolbar

**Comment by Hambrsoom** [comment]
Once you finish, show a picture of the template :)

**Comment by daphneaugier** [comment]
I was thinking of putting a toolbar with only the posts I posted and the posts I liked. So Posts/Likes

**Comment by daphneaugier** [comment]
Should we put other features in this toolbar?

**Comment by HussainWitwit** [comment]
<img width="1210" alt="screen shot 2019-02-17 at 5 16 01 pm" src="https://user-images.githubusercontent.com/40703467/52920232-53194300-32d8-11e9-9986-35923cc4b565.png">

for now we have the horizontal toolbar bellow the profile pictures, I was thinking on top of all the wits we are going to show we write "wits" as a title. When a user presses on followers, we will have "followers" in the title and then all the followers we appear bellow and so on for the following and the likes.  What do you think?

**Comment by daphneaugier** [comment]
So we do a toolbar like so : 
|       Wits     |      Likes       |       Followers        |       Following       |

**Comment by daphneaugier** [comment]
This means that we would have two ways to access the user's Followers/Following lists?  From the toolbar and also from the left side in purple right? I like the idea

**Comment by HussainWitwit** [comment]
no I think we should keep one tool bar, the vertical one might be enough unless you want to make it horizontal on top of the wits!

**Comment by RobertBeaudenon** [comment]
To populate the wits on the profile :
1- I created the' services ' Folder in profile with the required files.
2-The Array of object 'userWits' can be  directly used in the Html body to retrieve the wits.
3- I am also getting the Number of Likes for each userWit accessible with   'likesListProfile'

**Comment by daphneaugier** [comment]
We are still doing this feature for Sprint 3 or not?

**Comment by daphneaugier** [comment]
<img width="697" alt="capture d ecran 2019-03-03 a 21 07 32" src="https://user-images.githubusercontent.com/35980232/53706485-9dcaad00-3df8-11e9-9bd1-05ca94e74df7.png">
This is the tab with all the 4 different choices that can be accessed. Tell me if you like it like this!

**Comment by HussainWitwit** [comment]
Very nice, I think it's safe to say we can close this issue?
